name: ESP32 Project Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: Build ESP32 Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install pre-commit
      - run: make build
